// Generated by CoffeeScript 1.7.1
(function() {
  var app, root;

  this.wgMenuConfig = [
    {
      name: 'Hector',
      url: 'hector',
      description: 'A 3Dish pixelart head, and some buttons. What do they do?',
      hint: 'Play with the buttons, you\'ll figure it out.',
      img: 'hector.png'
    }, {
      name: 'Sprite Breaker',
      url: 'spriteBreaker',
      description: 'A tool for splitting spritesheets and injecting them into projects.',
      hint: 'Click the  "?" button for a quick start guide.',
      img: 'spriteBreaker.png'
    }, {
      name: 'Sombrero',
      url: 'sombrero',
      description: 'A 2.5D pixel art animation test.',
      hint: 'Use the arrow keys to move.',
      img: 'sombrero.png'
    }
  ];

  root = this;

  app = angular.module('bodyApp', ['ngSanitize']);

  app.directive('wgMainMenu', [
    function() {
      return {
        restrict: 'AEC',
        templateUrl: "/templates/wgMainMenu.html",
        replace: true,
        link: function(scope, element, attrs) {
          return scope.menuConfig = root.wgMenuConfig;
        }
      };
    }
  ]);

  angular.bootstrap(root.document.body, ["bodyApp"]);

}).call(this);
