// Generated by CoffeeScript 1.7.1
(function() {
  var app, miniNav, navAppElement, root;

  this.wgMenuConfig = [
    {
      name: 'Space Joust',
      url: 'spaceJoust',
      description: '*WIP* Multiplayer thumbwrestling(?) with lasers, in space.',
      hint: '<strong>Alien:</strong> WSAD & G | <strong>Human:</strong> Arrows & Period<br/> Land on your opponent\s head for maximum damage.',
      img: 'spaceJoust.png'
    }, {
      name: 'Hector',
      url: 'hector',
      description: 'A 3Dish pixelart head, and some buttons. What do they do?',
      hint: 'Play with the buttons, you\'ll figure it out.<br/><small>Featuring a nearly infinite number of unique blinks!</small>',
      img: 'hector.png'
    }, {
      name: 'Sprite Breaker',
      url: 'spriteBreaker',
      description: 'A tool for splitting spritesheets and injecting them into projects.',
      hint: 'Click the  "?" button for a quick start guide.',
      img: 'spriteBreaker.png'
    }, {
      name: 'Sombrero',
      url: 'sombrero',
      description: 'A 2.5D pixel art animation test.',
      hint: 'Use the arrow keys to move.',
      img: 'sombrero.png'
    }
  ];

  root = this;

  app = angular.module('navApp', ['ngSanitize']);

  app.directive('wgMiniMenu', [
    '$timeout', function($timeout) {
      return {
        restrict: 'AEC',
        templateUrl: "/templates/wgMiniMenu.html",
        replace: true,
        link: function(scope, element, attrs) {
          scope.menuConfig = root.wgMenuConfig.reduce(function(acc, item, i) {
            if (root.location.pathname === '/' + item.url + '/') {
              scope.project = item;
            } else {
              acc.push(item);
            }
            return acc;
          }, [
            {
              name: 'Home',
              url: '',
              description: 'Project index page'
            }
          ]);
          return root.addEventListener('mouseup', function(e) {
            if (!(element[0] !== e.target && element[0].contains(e.target))) {
              return $timeout(function() {
                scope.showProjects = false;
                return scope.showProject = false;
              });
            }
          });
        }
      };
    }
  ]);

  navAppElement = root.document.getElementById('wg-nav-app');

  miniNav = document.createElement('div');

  miniNav.className = 'wg-mini-menu';

  navAppElement.appendChild(miniNav);

  angular.bootstrap(navAppElement, ["navApp"]);

}).call(this);
