// Generated by CoffeeScript 1.7.1
(function() {
  var app, miniNav, root;

  this.wgMenuConfig = [
    {
      name: 'Hector',
      url: 'hector',
      description: 'A 3Dish pixelart head, and some buttons. What do they do?',
      hint: 'Play with the buttons, you\'ll figure it out.',
      img: 'hector.png'
    }, {
      name: 'Sprite Breaker',
      url: 'spriteBreaker',
      description: 'A tool for splitting spritesheets and injecting them into projects.',
      hint: 'Click the  "?" button for a quick start guide.',
      img: 'spriteBreaker.png'
    }, {
      name: 'Sombrero',
      url: 'sombrero',
      description: 'A 2.5D pixel art animation test.',
      hint: 'Use the arrow keys to move.',
      img: 'sombrero.png'
    }
  ];

  root = this;

  app = angular.module('navApp', []);

  app.directive('wgMiniMenu', [
    function() {
      return {
        restrict: 'AEC',
        templateUrl: "/templates/wgMiniMenu.html",
        replace: true,
        link: function(scope, element, attrs) {
          return scope.menuConfig = root.wgMenuConfig.reduce(function(acc, item, i) {
            if (root.location.pathname === '/' + item.url) {
              scope.project = item;
            } else {
              acc.push(item);
            }
            return acc;
          }, [
            {
              name: 'Home',
              url: '',
              description: 'Project index page'
            }
          ]);
        }
      };
    }
  ]);

  miniNav = document.createElement('div');

  miniNav.className = 'wg-mini-menu';

  root.document.body.appendChild(miniNav);

  app.run([
    '$rootElement', function(element) {
      return console.log(element);
    }
  ]);

}).call(this);
