// Generated by CoffeeScript 1.7.1
(function() {
  this.wgMenuConfig = [
    {
      name: 'Hector',
      url_suffix: 'hector',
      description: 'A 3Dish, pixelartish head with an attitude',
      img_src: 'hector.png'
    }, {
      name: 'Sprite Breaker',
      url_suffix: 'spriteBreaker',
      description: 'A tool for splitting spritesheets and injecting them into projects',
      img_src: 'spriteBreaker.png'
    }, {
      name: 'Sombrero',
      url_suffix: 'sombrero',
      description: 'A 2.5D pixel art test',
      img_src: 'sombrero.png'
    }
  ];

}).call(this);
